version: '2'

services:
    mysql:
        build: ./docker/mysql
        hostname: rm-mysql
        container_name: rm-mysql
        image: mikewolfxyou/rm-mysql
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        stdin_open: true
        tty: true

    redirect-middleware:
        build: .
        hostname: rm-go-lang-app
        container_name: redirect-middleware
        ports:
          - "3000:3000"
        image: mikewolfxyou/redirect
        stdin_open: true
        tty: true